### ISSUE TITLE
german translation updates send in from BeastXXL

### ISSUE THREAD

**Issue by mgerhardy** [ufoai/ufoai#33]
just received a mail with german po file updates - not sure for which version though.
[ufoai-de.po.zip](https://github.com/ufoai/ufoai/files/479477/ufoai-de.po.zip)

**Comment by DarkRainX** [comment]
Seems to be for an older 2.6, the *.po files have since been updated, but this is still quite usable, just re-running update-po over it, of course I don't speak German, so I can't comment on the actual translation...

**Comment by SR-71x2** [comment]
German Player here:
Translation quality seems good.

**Comment by DarkRainX** [comment]
Well then, I applied the file and then updated the po files, so it's ready for the next translators
