### ISSUE TITLE
ufoai 2.5 self compiled auto scroll

### ISSUE THREAD

**Issue by gr01d** [ufoai/ufoai#39]
I have compiled the UFOAI 2.5 stable from the https://ufoai.org/wiki/Download and https://ufoai.org/wiki/Debian for Trisquel 7 (based on Ubuntu 14.04). i have disabled testsuite and uforadiant in ./compile
Upon playing the game './ufo' in the  battlescape after my first move, the aliens move the screen just scrolls downward. It's like the alien movements were done but the screen just keeps moving, liike pressing the W key or arrow key indefinitely. I am still trying to find more information as of this moment. So far this has occurred to me twice in the first battlescape mission mode.

**Comment by zor1984qq** [comment]
It seems it rather ubuntu 14.04 problem rather then game itself...when I use such old system back in few years it has such issue in a few of games. Or maybe not. Just don't use such an outdated system. Or maybe its just hardware problem. I am not arguing about GNU "true" OS here but it still old and has a bugs. The only thing is maintained there is kernel and graphics stack with few security patches. So the libs or any system component can have a bugs.

**Comment by DarkRainX** [comment]
Does disabling the "Center View" option help?

**Comment by zor1984qq** [comment]
I don't know how to disable it and just using now default 2.5 packaged in manjaro. Sorry, I already delete my git cloned repo long time ago.14.10.2017, 18:52, "DarkRainX" <notifications@github.com>:Does disabling the "Center View" option help?

**Comment by gr01d** [comment]
@DarkRainX  I cannot test it further as I now use Debian 9. I will update this whenever I have the chance to use Trisquel 7 later tiime.
