### ISSUE TITLE
Issue tracker broken

### ISSUE THREAD

**Issue by FalcoGer** [ufoai/ufoai#54]
When opening any issue on the [official bugtracker](https://ufoai.org/bugs) I get the following error:

> Undefined variable: error
The following notice has stopped further execution:
Undefined variable: error in /home/mattn/htdocs/thebuggenie/core/templates/error.php, line 93

**Comment by AroKol78** [comment]
`https://ufoai.org/bugs/` is **error**

```
An error occurred in The Bug Genie

Function get_magic_quotes_gpc() is deprecated

The following error occured:
Function get_magic_quotes_gpc() is deprecated in /home/mattn/htdocs/thebuggenie/core/framework/Request.php, line 346
```

**Comment by DarkRainX** [comment]
Thanks for reporting.
